export const WEB3_LOADED = "WEB3_LOADED",
	WEB3_ACCOUNT_LOADED = "WEB3_ACCOUNT_LOADED",
	TOKEN_LOADED = "TOKEN_LOADED",
	EXCHANGE_LOADED = "EXCHANGE_LOADED",
	CANCELLED_ORDERS_LOADED = "CANCELLED_ORDERS_LOADED",
	FILLED_ORDERS_LOADED = "FILLED_ORDERS_LOADED",
	ALL_ORDERS_LOADED = "ALL_ORDERS_LOADED";
